### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by so-lost** [raguay/MoveToDir#2]
Trying to select files and then move to new directory but returns this error:

```
Command 'MoveToDir' raised error.

Traceback (most recent call last):
  File "fman/impl/fs_cache.py", line 36, in query
KeyError: 'stat'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Applications/fman.app/Contents/Resources/Plugins/Core/core/fs/local/__init__.py", line 52, in stat
    return os.stat(os_path)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/<username>/Pictures/Memes/testFolder'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "fman/impl/plugins/command_registry.py", line 110, in _execute_command
  File "/Users/<username>/Library/Application Support/fman/Plugins/Third-party/MoveToDir/movetodir/__init__.py", line 16, in __call__
    if not is_dir(newdirp):
  File "fman/fs.py", line 24, in is_dir
  File "fman/impl/plugins/mother_fs.py", line 62, in is_dir
  File "fman/impl/plugins/mother_fs.py", line 60, in query
  File "/Applications/fman.app/Contents/Resources/Plugins/Core/core/fs/local/__init__.py", line 45, in is_dir
    return S_ISDIR(self.stat(existing_path).st_mode)
  File "fman/fs.py", line 201, in wrapper
  File "fman/impl/fs_cache.py", line 12, in query
  File "fman/impl/fs_cache.py", line 38, in query
  File "fman/fs.py", line 201, in <lambda>
  File "/Applications/fman.app/Contents/Resources/Plugins/Core/core/fs/local/__init__.py", line 54, in stat
    return os.stat(os_path, follow_symlinks=False)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/<username>/Pictures/Memes/testFolder'
```

**Comment by raguay** [comment]
This error is a problem with the fman internal library. It isn't catching
the error if the file/directory doesn't exist. The error is in the call of
is_dir(). It should return false if the directory doesn't exist, but it is
trying to do a stat on it and stat is bombing with an error. Since my
plugin is using the fman API, the fix needs to be there. I added Michael to
this email for his advice.

**Comment by raguay** [comment]
I'm assuming your on macOS? Is this correct, or are you on a linux distro? The example path looks like macOS, but I could be linux. I've seen one linux distro set the user directory that way.

**Comment by raguay** [comment]
It should be fixed. For some reason, it works on my system, but it shouldn't. The API does call for a catching of the exception. I added the except catching and it should be fine to go. Update the plugins and give it a try.
